[package]
name = "rust_rmm_agent"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "=0.29.10"
simplelog = "0.12"
log = "0.4"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"